easy_admin:
    design:
        assets:
            css:
                - 'css/admin.css'
        brand_color: '#1ABC9C'
    entities:
#        # List the entity class name you want to manage
        User:
            edit:
              - { property: 'password', type: 'text', type_options: { required: false, empty_data: '' } }
            #  - { property: 'photo', type: 'file_upload', type_options: {upload_dir: 'public/uploaded',upload_filename: '[uuid].[extension]' }}