twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        icon_service: '@App\Service\IconGenerator'
        image_directory: '/uploads/profile/'